# _config.yml
title: "NOOOB Tech Blog"
description: "网络安全 · 技术开发 · 日常笔记"
author: "DyNooob"
baseurl: ""
url: "https://dynooob.github.io"

# 主题
remote_theme: pages-themes/hacker@v0.2.0

# 语言
lang: zh-CN
timezone: Asia/Shanghai

# 文章设置
permalink: /posts/:title/

# 构建
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# 插件
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# 默认值
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true